plugins {
    id 'com.android.application'
}

android {
    namespace 'com.envarg.shibotc'
    compileSdk 35

    defaultConfig {
        applicationId "com.envarg.shibotc"
        minSdk 24
        targetSdk 35
        versionCode 10
        versionName "10.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}
