package com.gaurav.datasave;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.net.*;import android.view.*;import android.widget.*;import org.json.*;
public class MainActivity extends Activity{
 LinearLayout root,list; android.content.SharedPreferences sp; int N=Color.rgb(0,255,90),D=Color.rgb(0,19,15),P=Color.rgb(3,45,36);
 int dp(float x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}
 GradientDrawable box(int c,float r,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));if(stroke>0)g.setStroke(dp(stroke),N);return g;}
 TextView tv(String s,float z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.WHITE);v.setPadding(dp(10),dp(7),dp(10),dp(7));v.setGravity(Gravity.CENTER_VERTICAL);return v;}
 EditText field(String h){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(Color.rgb(185,200,195));e.setTextColor(Color.WHITE);e.setTextSize(14);e.setSingleLine();e.setPadding(dp(13),0,dp(13),0);e.setBackground(box(Color.argb(225,2,42,34),12,1));return e;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setTextSize(12);b.setBackground(box(Color.rgb(0,83,54),14,1));return b;}
 public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("shops",0);home();}
 void home(){ScrollView sc=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(12),dp(12),dp(12),dp(20));GradientDrawable grd=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(0,12,9),Color.rgb(0,48,31),Color.rgb(0,15,11)});root.setBackground(grd);
 LinearLayout head=new LinearLayout(this);TextView menu=tv("☰",27);head.addView(menu,new LinearLayout.LayoutParams(dp(48),dp(55)));TextView logo=tv("GAURAV\nDATA SAVE",28);logo.setTextColor(N);logo.setGravity(Gravity.CENTER);logo.setTypeface(Typeface.DEFAULT_BOLD);head.addView(logo,new LinearLayout.LayoutParams(0,dp(85),1));TextView shield=tv("🛡\nSecure",11);shield.setTextColor(N);shield.setGravity(Gravity.CENTER);head.addView(shield,new LinearLayout.LayoutParams(dp(70),dp(70)));root.addView(head);
 TextView tag=tv("SAVE TODAY  •  GROW TOMORROW",12);tag.setGravity(Gravity.CENTER);root.addView(tag);
 TextView hero=tv("⌖\n🏪",38);hero.setGravity(Gravity.CENTER);hero.setTextColor(N);hero.setBackground(box(Color.argb(90,0,255,80),55,1));LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-1,dp(110));hp.setMargins(dp(75),dp(8),dp(75),dp(8));root.addView(hero,hp);
 addStats();
 EditText search=field("⌕   Search shop, phone, area, category...");LinearLayout.LayoutParams spm=new LinearLayout.LayoutParams(-1,dp(52));spm.setMargins(0,dp(8),0,dp(8));root.addView(search,spm);
 TextView at=tv("⊕  Add Shop / Party",20);at.setTextColor(N);at.setTypeface(Typeface.DEFAULT_BOLD);root.addView(at);
 LinearLayout r1=new LinearLayout(this),r2=new LinearLayout(this),r3=new LinearLayout(this);EditText name=field("🏪  Shop / Party Name"),phone=field("☎  Phone Number"),maps=field("🔗  Google Maps Location / Link"),area=field("⌖  Area (e.g. Paharganj, Delhi)"),cat=field("▦  Category"),note=field("✎  Note (optional)");pair(r1,name,phone);pair(r2,maps,area);pair(r3,cat,note);root.addView(r1);root.addView(r2);root.addView(r3);
 Button save=btn("▣   SAVE LOCATION");save.setTextSize(17);save.setTypeface(Typeface.DEFAULT_BOLD);LinearLayout.LayoutParams sv=new LinearLayout.LayoutParams(-1,dp(58));sv.setMargins(0,dp(8),0,dp(10));root.addView(save,sv);
 LinearLayout lh=new LinearLayout(this);TextView st=tv("SAVED SHOPS",18);st.setTextColor(N);st.setTypeface(Typeface.DEFAULT_BOLD);lh.addView(st,new LinearLayout.LayoutParams(0,dp(48),1));Button sort=btn("Sort: Newest⌄");lh.addView(sort,new LinearLayout.LayoutParams(dp(125),dp(44)));root.addView(lh);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);
 save.setOnClickListener(v->{if(name.getText().toString().trim().isEmpty()){Toast.makeText(this,"Shop name required",0).show();return;}try{JSONArray a=new JSONArray(sp.getString("data","[]"));JSONObject o=new JSONObject();o.put("n",name.getText().toString());o.put("p",phone.getText().toString());o.put("m",maps.getText().toString());o.put("a",area.getText().toString());o.put("c",cat.getText().toString());o.put("no",note.getText().toString());o.put("time",System.currentTimeMillis());a.put(o);sp.edit().putString("data",a.toString()).apply();home();}catch(Exception e){}});
 search.setOnEditorActionListener((v,id,event)->{render(search.getText().toString());return false;});render("");
 LinearLayout nav=new LinearLayout(this);String[] ns={"⌂\nHome","＋\nAdd","⌖\nMap","▥\nReports","⚙\nMore"};for(String x:ns){TextView z=tv(x,12);z.setGravity(Gravity.CENTER);z.setTextColor(x.contains("Home")?N:Color.LTGRAY);nav.addView(z,new LinearLayout.LayoutParams(0,dp(62),1));}nav.setBackground(box(Color.argb(245,1,37,29),16,1));root.addView(nav);sc.addView(root);setContentView(sc);}
 void pair(LinearLayout r,View a,View b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(52),1);p.setMargins(dp(2),dp(4),dp(2),dp(4));r.addView(a,p);r.addView(b,p);}
 void addStats(){LinearLayout r=new LinearLayout(this);String[] a={"🏪\nTotal Shops","👥\nVisited","★\nFavourites","▣\nToday"};int[] cs={Color.rgb(0,100,54),Color.rgb(0,92,170),Color.rgb(180,125,0),Color.rgb(103,32,154)};for(int i=0;i<4;i++){TextView x=tv(a[i],12);x.setGravity(Gravity.CENTER);x.setTypeface(Typeface.DEFAULT_BOLD);x.setBackground(box(cs[i],14,1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(70),1);p.setMargins(dp(2),0,dp(2),0);r.addView(x,p);}root.addView(r);}
 void render(String q){list.removeAllViews();try{JSONArray a=new JSONArray(sp.getString("data","[]"));for(int i=a.length()-1;i>=0;i--){JSONObject o=a.getJSONObject(i);if(!q.isEmpty()&&!o.toString().toLowerCase().contains(q.toLowerCase()))continue;LinearLayout c=new LinearLayout(this);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(10),dp(7),dp(8),dp(7));c.setBackground(box(Color.argb(238,2,42,34),13,1));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(78));cp.setMargins(0,dp(3),0,dp(3));c.setLayoutParams(cp);TextView info=tv(o.optString("n")+"  ★\n☎ "+o.optString("p")+"\n⌖ "+o.optString("a"),13);info.setTypeface(Typeface.DEFAULT_BOLD);c.addView(info,new LinearLayout.LayoutParams(0,-1,1));String ph=o.optString("p"),mp=o.optString("m");Button call=btn("☎");call.setOnClickListener(v->startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+ph))));c.addView(call,new LinearLayout.LayoutParams(dp(48),dp(48)));Button wa=btn("W");wa.setOnClickListener(v->{String z=ph.replaceAll("\\D","");if(z.length()==10)z="91"+z;startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://wa.me/"+z)));});c.addView(wa,new LinearLayout.LayoutParams(dp(48),dp(48)));Button map=btn("⌖");map.setOnClickListener(v->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(mp)));}catch(Exception e){}});c.addView(map,new LinearLayout.LayoutParams(dp(48),dp(48)));list.addView(c);}}catch(Exception e){}}
}