package com.gaurav.datasave;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.net.*;import android.view.*;import android.view.inputmethod.*;import android.widget.*;import org.json.*;
public class MainActivity extends Activity{
 LinearLayout list,root; android.content.SharedPreferences sp; int neon=Color.rgb(0,255,91),panel=Color.rgb(4,47,38),dark=Color.rgb(0,25,20);
 int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
 GradientDrawable box(int color,float r,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(r));if(stroke>0)g.setStroke(dp(1),neon);return g;}
 TextView text(String s,float z){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setGravity(Gravity.CENTER_VERTICAL);v.setPadding(dp(12),dp(8),dp(12),dp(8));return v;}
 EditText field(String h){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(Color.rgb(170,190,184));e.setTextColor(Color.WHITE);e.setTextSize(16);e.setSingleLine(true);e.setPadding(dp(14),0,dp(14),0);e.setBackground(box(Color.argb(220,5,48,39),14,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(50));lp.setMargins(0,dp(5),0,dp(5));e.setLayoutParams(lp);return e;}
 Button button(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(13);b.setAllCaps(false);b.setBackground(box(Color.rgb(0,92,61),15,1));return b;}
 public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("shops",0);draw();}
 void circuitBg(){GradientDrawable gd=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(0,18,14),Color.rgb(0,45,32),Color.rgb(0,20,16)});root.setBackground(gd);}
 void draw(){ScrollView sc=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(18),dp(14),dp(30));circuitBg();
 TextView logo=text("GAURAV\nDATA SAVE",32);logo.setTextColor(neon);logo.setGravity(Gravity.CENTER);logo.setTypeface(Typeface.create("sans-serif",Typeface.BOLD));root.addView(logo);
 TextView tag=text("SAVE TODAY  •  GROW TOMORROW",13);tag.setGravity(Gravity.CENTER);tag.setTextColor(Color.rgb(205,230,220));root.addView(tag);
 LinearLayout stats=new LinearLayout(this);stats.setPadding(0,dp(8),0,dp(8));String[] s={"▣\nTotal","●●\nVisited","★\nFavourites","●\nToday"};for(String z:s){TextView x=text(z,12);x.setGravity(Gravity.CENTER);x.setTextColor(neon);x.setBackground(box(Color.argb(225,3,57,45),14,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(62),1);lp.setMargins(dp(2),0,dp(2),0);stats.addView(x,lp);}root.addView(stats);
 EditText search=field("⌕  Search shop, phone, area, category...");root.addView(search);
 TextView add=text("＋  ADD SHOP / PARTY",20);add.setTextColor(neon);add.setTypeface(Typeface.DEFAULT_BOLD);LinearLayout.LayoutParams alp=new LinearLayout.LayoutParams(-1,-2);alp.setMargins(0,dp(10),0,dp(4));root.addView(add,alp);
 EditText n=field("Shop / Party Name");root.addView(n);EditText p=field("Phone Number");p.setInputType(3);root.addView(p);EditText m=field("Google Maps Location / Link");root.addView(m);EditText a=field("Area  (e.g. Paharganj, Delhi)");root.addView(a);EditText c=field("Category");root.addView(c);EditText no=field("Note (optional)");root.addView(no);
 Button save=button("SAVE LOCATION");save.setTextSize(17);save.setTypeface(Typeface.DEFAULT_BOLD);LinearLayout.LayoutParams slp=new LinearLayout.LayoutParams(-1,dp(56));slp.setMargins(0,dp(8),0,dp(10));root.addView(save,slp);
 TextView title=text("SAVED SHOPS",18);title.setTextColor(neon);title.setTypeface(Typeface.DEFAULT_BOLD);root.addView(title);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);
 save.setOnClickListener(v->{if(n.getText().toString().trim().isEmpty()){Toast.makeText(this,"Shop name required",Toast.LENGTH_SHORT).show();return;}try{JSONArray ar=new JSONArray(sp.getString("data","[]"));JSONObject o=new JSONObject();o.put("n",n.getText().toString());o.put("p",p.getText().toString());o.put("m",m.getText().toString());o.put("a",a.getText().toString());o.put("c",c.getText().toString());o.put("no",no.getText().toString());ar.put(o);sp.edit().putString("data",ar.toString()).apply();draw();}catch(Exception e){}});
 search.setOnEditorActionListener((v,id,event)->{render(search.getText().toString());return false;});render("");sc.addView(root);setContentView(sc);}
 void render(String q){list.removeAllViews();try{JSONArray ar=new JSONArray(sp.getString("data","[]"));for(int i=ar.length()-1;i>=0;i--){JSONObject o=ar.getJSONObject(i);if(!q.isEmpty()&&!o.toString().toLowerCase().contains(q.toLowerCase()))continue;LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(12),dp(8),dp(12),dp(8));card.setBackground(box(Color.argb(235,3,49,39),16,1));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,dp(5),0,dp(5));card.setLayoutParams(cp);TextView h=text(o.optString("n"),18);h.setTextColor(neon);h.setTypeface(Typeface.DEFAULT_BOLD);card.addView(h);card.addView(text(o.optString("p")+"   •   "+o.optString("a")+"\n"+o.optString("c")+"   "+o.optString("no"),13));LinearLayout row=new LinearLayout(this);String ph=o.optString("p"),mp=o.optString("m");Button call=button("☎ Call");call.setOnClickListener(v->startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+ph))));row.addView(call,new LinearLayout.LayoutParams(0,dp(48),1));Button wa=button("WhatsApp");wa.setOnClickListener(v->{String z=ph.replaceAll("\\D","");if(z.length()==10)z="91"+z;startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://wa.me/"+z)));});row.addView(wa,new LinearLayout.LayoutParams(0,dp(48),1));Button map=button("⌖ Map");map.setOnClickListener(v->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(mp)));}catch(Exception e){}});row.addView(map,new LinearLayout.LayoutParams(0,dp(48),1));card.addView(row);list.addView(card);}}catch(Exception e){}}
}